# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjBhYjEwMmIzMDdjMjRlZjI5NDg5YjMzYmY5ZjJjZWNlMzdiNDZlN2Y5ZjkyNmM1NGJiMmM0ZWVlNzE4ZGUwMjQ5NDI2NTg1MDNkZGU1NGYzMDk0MDZiMjg4ODY2ZTMwNDVmYWE0N2FlOTNjNGJjODQ5YjRhMmM3NjhkODE2OGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
